web:
    build: ./
    ports:
        - "8080:80"
    expose:
        - "80"
    volumes:
        - ./:/var/www/html/
        - ./docker/vhosts/:/etc/apache2/sites-enabled/
        - $SSH_AUTH_SOCK:/tmp/agent.sock
    links:
        - mysql
        - redis
        - seleniumhub
    environment:
        - SSH_AUTH_SOCK=/tmp/agent.sock
        - TERM=xterm-256color
    extra_hosts:
      - "backend.local:127.0.0.1"
      - "frontend.local:127.0.0.1"
      
mysql:
  image: mysql:5.6
  ports:
    - "3316:3306"
  expose:
    - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: secret-root
    MYSQL_DATABASE: web
    MYSQL_USER: web
    MYSQL_PASSWORD: web
    
redis:
  image: redis:2
  command: /usr/local/bin/mongod --smallfiles
  ports:
    - "6389:6379"
    
seleniumhub:
  image: selenium/hub

seleniumfirefox:
  image: selenium/node-firefox-debug
  links:
    - seleniumhub:hub
    - php
  ports:
    - "49338:5900"
