web:
    build: ./
    ports:
        - "8080:80"
    expose:
        - "80"
    volumes:
        - ./:/var/www/html/
        - ./docker/vhosts/:/etc/apache2/sites-enabled/
    links:
        - mysql
        - redis
    environment:
        ENABLE_ENV_FILE: 1
        ENABLE_LOCALCONF: 1
    extra_hosts:
      - "backend.local:127.0.0.1"
      - "frontend.local:127.0.0.1"

mysql:
  image: mysql:5.6
  ports:
    - "3316:3306"
  expose:
    - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: secret-root
    MYSQL_DATABASE: web
    MYSQL_USER: web
    MYSQL_PASSWORD: web
redis:
  image: redis
  ports:
    - "6389:6379"
