# ~/.bashrc: executed by bash(1) for non-login shells.

# Note: PS1 and umask are already set in /etc/profile. You should not
# need this unless you want different defaults for root.
# PS1='${debian_chroot:+($debian_chroot)}\h:\w\$ '
# umask 022

# You may uncomment the following lines if you want `ls' to be colorized:
export LS_OPTIONS='--color=auto'
# eval "`dircolors`"
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -l'
alias l='ls $LS_OPTIONS -lA'
#
# Some more alias to avoid making mistakes:
# alias rm='rm -i'
# alias cp='cp -i'
# alias mv='mv -i'

alias mysql='mysql -uroot -h $APP_MYSQL_1_PORT_3306_TCP_ADDR -P $APP_MYSQL_1_PORT_3306_TCP_PORT'

export PATH=/var/www/vendor/bin:$PATH

# term
if [ -f /dev/tty ]; then
    exec >/dev/tty 2>/dev/tty </dev/tty
    export TERM=screen-256color
fi
